name: Deploy Shopify App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Check Node Version
        run: node -v

      - name: Install dependencies
        run: npm install

      - - name: Deploy Shopify App
  run: |
    npm install -g @shopify/cli @shopify/app
    shopify app deploy --allow-updates
  env:
    SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
    SHOPIFY_API_SECRET: ${{ secrets.SHOPIFY_API_SECRET }}
    SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_FLAG_STORE }}